Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/mozillavpn.xliff -OutFile D:\Temp\mozillavpn.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_01_how_to_vpn/strings.xliff -OutFile D:\Temp\addons-guide_01_how_to_vpn-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_02_is_my_vpn_working_correctly/strings.xliff -OutFile D:\Temp\addons-guide_02_is_my_vpn_working_correctly.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_03_adding_and_removing_devices/strings.xliff -OutFile D:\Temp\addons-guide_03_adding_and_removing_devices-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_05_what_is_multi_hop/strings.xliff -OutFile D:\Temp\addons-guide_05_what_is_multi_hop-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_08_privacy_features/strings.xliff -OutFile D:\Temp\addons-guide_08_privacy_features-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_09_custom_dns/strings.xliff -OutFile D:\Temp\addons-guide_09_custom_dns-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_10_app_exclusions/strings.xliff -OutFile D:\Temp\addons-guide_10_app_exclusions-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_11_recommended_servers/strings.xliff -OutFile D:\Temp\addons-guide_11_recommended_servers-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/guide_12_multi_account_containers/strings.xliff -OutFile D:\Temp\addons-guide_12_multi_account_containers-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_subscription_expiring/strings.xliff -OutFile D:\Temp\addons-message_subscription_expiring-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_survey/strings.xliff -OutFile D:\Temp\addons-message_survey-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_update_v2.15/strings.xliff -OutFile D:\Temp\addons-message_update_v2.15-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_update_v2.17/strings.xliff -OutFile D:\Temp\addons-message_update_v2.17-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_update_v2.18/strings.xliff -OutFile D:\Temp\addons-message_update_v2.18-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_update_v2.19/strings.xliff -OutFile D:\Temp\addons-message_update_v2.19-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_upgrade_to_annual_plan/strings.xliff -OutFile D:\Temp\addons-message_upgrade_to_annual_plan-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_whats_new_v2.15/strings.xliff -OutFile D:\Temp\addons-message_whats_new_v2.15-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_whats_new_v2.16/strings.xliff -OutFile D:\Temp\addons-message_whats_new_v2.16-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_whats_new_v2.17/strings.xliff -OutFile D:\Temp\addons-message_whats_new_v2.17-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_whats_new_v2.18/strings.xliff -OutFile D:\Temp\addons-message_whats_new_v2.18-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/message_whats_new_v2.19/strings.xliff -OutFile D:\Temp\addons-message_whats_new_v2.19-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/tutorial_01_get_started_recommended_locations/strings.xliff -OutFile D:\Temp\addons-tutorial_01_get_started_recommended_locations-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/tutorial_01_get_started/strings.xliff -OutFile D:\Temp\addons-tutorial_01_get_started-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/tutorial_02_connect_on_startup/strings.xliff -OutFile D:\Temp\addons-tutorial_02_connect_on_startup-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/tutorial_03_multi_hop/strings.xliff -OutFile D:\Temp\addons-tutorial_03_multi_hop-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-client-l10n/raw/main/en/addons/tutorial_04_split_tunneling3/strings.xliff -OutFile D:\Temp\addons-tutorial_04_split_tunneling3-strings.xliff
Invoke-WebRequest -Uri https://github.com/mozilla-l10n/mozilla-vpn-website-l10n/raw/main/en-US/vpn.ftl -OutFile D:\Temp\vpn.ftl
